-- Canonical Cloudflare D1 schema for the rope-jump registration application.
-- UUID values are TEXT and are generated by the Worker before INSERT.
-- Timestamps are UTC ISO-8601 TEXT. JSON values are stored as validated TEXT.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS competitions (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  subtitle TEXT,
  venue TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  registration_deadline TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','open','closed','completed')),
  description TEXT,
  logo_url TEXT,
  max_individual_events INTEGER CHECK (max_individual_events IS NULL OR max_individual_events >= 0),
  max_team_events INTEGER CHECK (max_team_events IS NULL OR max_team_events >= 0),
  individual_registration_enabled INTEGER NOT NULL DEFAULT 0 CHECK (individual_registration_enabled IN (0,1)),
  individual_open_at TEXT,
  individual_deadline TEXT,
  individual_form_schema TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(individual_form_schema) AND json_type(individual_form_schema) = 'array'),
  individual_notes TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY NOT NULL,
  competition_id TEXT NOT NULL,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  max_athletes INTEGER NOT NULL DEFAULT 1 CHECK (max_athletes > 0),
  is_individual INTEGER NOT NULL DEFAULT 1 CHECK (is_individual IN (0,1)),
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (competition_id, code),
  UNIQUE (competition_id, id)
);

CREATE TABLE IF NOT EXISTS event_groups (
  id TEXT PRIMARY KEY NOT NULL,
  event_id TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('gender','age','level','team')),
  gender TEXT CHECK (gender IS NULL OR gender IN ('male','female','mixed')),
  age_min INTEGER CHECK (age_min IS NULL OR age_min >= 0),
  age_max INTEGER CHECK (age_max IS NULL OR age_max >= 0),
  max_registrations INTEGER NOT NULL DEFAULT 20 CHECK (max_registrations >= 0),
  current_count INTEGER NOT NULL DEFAULT 0 CHECK (current_count >= 0),
  order_index INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (event_id) REFERENCES events(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CHECK (age_min IS NULL OR age_max IS NULL OR age_min <= age_max),
  UNIQUE (event_id, name),
  UNIQUE (event_id, id)
);

CREATE TABLE IF NOT EXISTS clubs (
  id TEXT PRIMARY KEY NOT NULL,
  username TEXT NOT NULL COLLATE NOCASE,
  password_hash TEXT NOT NULL CHECK (length(password_hash) > 0),
  club_name TEXT NOT NULL,
  contact_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  province TEXT,
  city TEXT,
  is_approved INTEGER NOT NULL DEFAULT 1 CHECK (is_approved IN (0,1)),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS team_profiles (
  id TEXT PRIMARY KEY NOT NULL,
  club_id TEXT NOT NULL,
  competition_id TEXT NOT NULL,
  team_name TEXT NOT NULL,
  slogan TEXT,
  logo_url TEXT,
  max_athletes INTEGER CHECK (max_athletes IS NULL OR max_athletes >= 0),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (club_id, competition_id, team_name),
  UNIQUE (club_id, competition_id, id)
);

CREATE TABLE IF NOT EXISTS team_leaders (
  id TEXT PRIMARY KEY NOT NULL,
  club_id TEXT NOT NULL,
  competition_id TEXT NOT NULL,
  team_profile_id TEXT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  position TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (team_profile_id) REFERENCES team_profiles(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS coaches (
  id TEXT PRIMARY KEY NOT NULL,
  club_id TEXT NOT NULL,
  competition_id TEXT NOT NULL,
  team_profile_id TEXT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  certificate TEXT,
  level TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (team_profile_id) REFERENCES team_profiles(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS athletes (
  id TEXT PRIMARY KEY NOT NULL,
  club_id TEXT NOT NULL,
  competition_id TEXT NOT NULL,
  team_profile_id TEXT,
  name TEXT NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('male','female','mixed')),
  birth_date TEXT NOT NULL,
  id_card TEXT NOT NULL,
  phone TEXT,
  avatar_url TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (team_profile_id) REFERENCES team_profiles(id) ON UPDATE CASCADE ON DELETE SET NULL,
  UNIQUE (competition_id, id_card)
);

CREATE TABLE IF NOT EXISTS registrations (
  id TEXT PRIMARY KEY NOT NULL,
  competition_id TEXT NOT NULL,
  club_id TEXT NOT NULL,
  team_profile_id TEXT,
  club_name TEXT NOT NULL,
  event_id TEXT NOT NULL,
  event_name TEXT NOT NULL,
  group_id TEXT NOT NULL,
  group_name TEXT NOT NULL,
  athletes TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(athletes) AND json_type(athletes) = 'array'),
  coach_id TEXT,
  coach_name TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','rejected')),
  reject_reason TEXT,
  start_order INTEGER,
  bib_number TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (team_profile_id) REFERENCES team_profiles(id) ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (competition_id, event_id) REFERENCES events(competition_id, id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (event_id, group_id) REFERENCES event_groups(event_id, id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (coach_id) REFERENCES coaches(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS order_entries (
  id TEXT PRIMARY KEY NOT NULL,
  competition_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  event_name TEXT NOT NULL,
  group_id TEXT NOT NULL,
  group_name TEXT NOT NULL,
  start_order INTEGER NOT NULL CHECK (start_order > 0),
  session_label TEXT,
  session_number INTEGER,
  venue_number INTEGER,
  bib_number TEXT NOT NULL,
  club_id TEXT NOT NULL,
  club_name TEXT NOT NULL,
  athletes TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(athletes) AND json_type(athletes) = 'array'),
  coach_name TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (competition_id, event_id) REFERENCES events(competition_id, id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (event_id, group_id) REFERENCES event_groups(event_id, id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (club_id) REFERENCES clubs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (competition_id, start_order)
);

CREATE TABLE IF NOT EXISTS admin_users (
  id TEXT PRIMARY KEY NOT NULL,
  username TEXT NOT NULL COLLATE NOCASE,
  password_hash TEXT NOT NULL CHECK (length(password_hash) > 0),
  display_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin','organizer')),
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  reset_required INTEGER NOT NULL DEFAULT 0 CHECK (reset_required IN (0,1)),
  reset_metadata TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(reset_metadata) AND json_type(reset_metadata) = 'object'),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS limit_configs (
  id TEXT PRIMARY KEY NOT NULL,
  competition_id TEXT NOT NULL,
  scope TEXT NOT NULL CHECK (scope IN ('team','event','group')),
  target_id TEXT NOT NULL,
  max_registrations INTEGER CHECK (max_registrations IS NULL OR max_registrations >= 0),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (competition_id, scope, target_id)
);

CREATE TABLE IF NOT EXISTS individual_registrations (
  id TEXT PRIMARY KEY NOT NULL,
  competition_id TEXT NOT NULL,
  name TEXT NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('male','female')),
  birth_date TEXT NOT NULL,
  id_card TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  province TEXT,
  city TEXT,
  address TEXT,
  events TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(events) AND json_type(events) = 'array'),
  custom_fields TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(custom_fields) AND json_type(custom_fields) = 'object'),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','rejected')),
  reject_reason TEXT,
  reviewed_by TEXT,
  reviewed_at TEXT,
  remark TEXT,
  source TEXT NOT NULL DEFAULT 'web',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (competition_id, id_card)
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY NOT NULL,
  token_hash TEXT NOT NULL,
  user_type TEXT NOT NULL CHECK (user_type IN ('admin','club')),
  user_id TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  last_seen_at TEXT NOT NULL,
  revoked_at TEXT,
  ip_hash TEXT,
  user_agent TEXT,
  UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY NOT NULL,
  actor_type TEXT NOT NULL CHECK (actor_type IN ('public','admin','club','system')),
  actor_id TEXT,
  action TEXT NOT NULL,
  table_name TEXT,
  record_id TEXT,
  request_id TEXT NOT NULL,
  metadata TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata) AND json_type(metadata) = 'object'),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Unique and query indexes. UNIQUE constraints already create SQLite auto-indexes.
CREATE INDEX IF NOT EXISTS idx_competitions_status_dates ON competitions(status, start_date, registration_deadline);
CREATE INDEX IF NOT EXISTS idx_events_competition_order ON events(competition_id, order_index);
CREATE INDEX IF NOT EXISTS idx_event_groups_event_order ON event_groups(event_id, order_index);
CREATE INDEX IF NOT EXISTS idx_clubs_created ON clubs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_team_profiles_competition ON team_profiles(competition_id, club_id);
CREATE INDEX IF NOT EXISTS idx_team_leaders_club_comp_team ON team_leaders(club_id, competition_id, team_profile_id);
CREATE INDEX IF NOT EXISTS idx_team_leaders_competition_name ON team_leaders(competition_id, name);
CREATE INDEX IF NOT EXISTS idx_coaches_club_comp_team ON coaches(club_id, competition_id, team_profile_id);
CREATE INDEX IF NOT EXISTS idx_coaches_competition_name ON coaches(competition_id, name);
CREATE INDEX IF NOT EXISTS idx_athletes_club_comp_team ON athletes(club_id, competition_id, team_profile_id);
CREATE INDEX IF NOT EXISTS idx_athletes_competition_name ON athletes(competition_id, name);
CREATE INDEX IF NOT EXISTS idx_registrations_comp_status_created ON registrations(competition_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_registrations_club_team_created ON registrations(club_id, team_profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_registrations_event_group ON registrations(event_id, group_id);
CREATE INDEX IF NOT EXISTS idx_order_entries_comp_order ON order_entries(competition_id, start_order);
CREATE INDEX IF NOT EXISTS idx_order_entries_club ON order_entries(club_id, competition_id);
CREATE INDEX IF NOT EXISTS idx_limit_configs_comp_scope ON limit_configs(competition_id, scope);
CREATE INDEX IF NOT EXISTS idx_limit_configs_target ON limit_configs(target_id);
CREATE INDEX IF NOT EXISTS idx_individual_reg_comp_status_created ON individual_registrations(competition_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_individual_reg_phone_created ON individual_registrations(phone, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_type, user_id, revoked_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_created ON audit_logs(actor_type, actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_table_record ON audit_logs(table_name, record_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_request ON audit_logs(request_id);

-- Keep event_groups.current_count consistent with registrations in the same D1 transaction.
CREATE TRIGGER IF NOT EXISTS trg_registrations_capacity_before_insert
BEFORE INSERT ON registrations
WHEN COALESCE((SELECT current_count >= max_registrations FROM event_groups WHERE id = NEW.group_id), 1)
BEGIN
  SELECT RAISE(ABORT, 'GROUP_CAPACITY_EXCEEDED');
END;

CREATE TRIGGER IF NOT EXISTS trg_registrations_count_after_insert
AFTER INSERT ON registrations
BEGIN
  UPDATE event_groups
  SET current_count = current_count + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
  WHERE id = NEW.group_id;
END;

CREATE TRIGGER IF NOT EXISTS trg_registrations_count_after_delete
AFTER DELETE ON registrations
BEGIN
  UPDATE event_groups
  SET current_count = MAX(0, current_count - 1),
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
  WHERE id = OLD.group_id;
END;

CREATE TRIGGER IF NOT EXISTS trg_registrations_count_after_group_change
AFTER UPDATE OF group_id ON registrations
WHEN OLD.group_id <> NEW.group_id
BEGIN
  UPDATE event_groups
  SET current_count = MAX(0, current_count - 1),
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
  WHERE id = OLD.group_id;
  UPDATE event_groups
  SET current_count = current_count + 1,
      updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
  WHERE id = NEW.group_id;
END;

-- Default administrator. Password: ropejump2024 (legacy SHA-256 compatibility).
-- reset_required and reset_metadata intentionally force an integration/UI follow-up reset.
INSERT OR IGNORE INTO admin_users (
  id, username, password_hash, display_name, role, is_active, reset_required, reset_metadata
) VALUES (
  '00000000-0000-4000-8000-000000000001',
  'admin',
  '5be95a707bb481504c74705d35755c6138732fbce540a33f5c487fd1b43f977f',
  '系统管理员',
  'admin',
  1,
  1,
  '{"reason":"default_credential","required_since":"initial_migration"}'
);
